version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin1234!
      MYSQL_DATABASE: AMS
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin1234!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  ams:
    build:
      context: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  db_data:
